version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000


# <---------- Below code is required when launching a postgresql server not hosted on AWS ---------->
#     depends_on:
#       - db
#   db:
#     image: postgres:13
#     volumes:
#       - postgres_data:/var/lib/postgresql/data/
#     environment:
#       - "POSTGRES_HOST_AUTH_METHOD=trust"

# volumes:
  # postgres_data: